### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by kerolloz** [Waelahmed99/8bit-Snake#1]
- [x] Add `Escape` button as exit button 
- [x] I would prefer `Return` (a.k.a `Enter`) button as the start button instead of `X` 
- [x] encapsulate snake as an object of a class `Snake`
- [x] same encapsulation for egg
- [x] drawing an egg may lead to a collision with the snake's body, you need to make sure that the new position of the egg won't collide with the body of the snake
- [x] use `.gitignore`, [click](https://github.com/github/gitignore/blob/master/C%2B%2B.gitignore) for more
- [x] since you're using *CLion*, check [this](https://www.jetbrains.com/help/clion/reformat-and-rearrange-code.html#) for more

**Comment by Waelahmed99** [comment]
Thanks kerolloz
Your issue was taken into consideration and solved here:
https://github.com/Waelahmed99/Gold

Please note that this repository may be deleted soon
Follow the previous link for the new one.

**Comment by kerolloz** [comment]
Good job :heart: 
consider archiving the repository instead of deleting it.
